config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    # sessions: 'users/sessions'
  }
  # get 'users/new'
  root   'static_pages#home'
  get    "/microposts",    to: "static_pages#home"

  devise_scope :user do
    get    "/sign_in",  to: "devise/sessions#new"
    post   "/sign_in",  to: "devise/sessions#create"
    delete "/sign_out", to: "devise/sessions#destroy"
    get    "/sign_up",  to: "users/registrations#new"
    post   "/sign_up",  to: "users/registrations#create"
    get    "/edit",     to: "users/registrations#edit"
    delete "/cancel",   to: "users/registrations#cancel"
  end 

  resources :users
  resources :children, only: [:index, :create]
  resources :wishlists, only: [:new, :index, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user

  # validates :due_date, presence: true
  # validates :due_date, presence: true, comparison: { greater_than: :Date.today }
  validates :due_date, presence: true
  validate :due_date_cannot_be_in_the_past, on: :create
  validates :list, presence: true, length: { 
    maximum: 50, wrong_length: "%{count}文字以下"
  }

  def due_date_cannot_be_in_the_past
    if due_date.present? && due_date < Date.today
      errors.add(:due_date, "（過去の日付は使えません）")
    end
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController

  before_action :authenticate_user!, only: [:index, :new, :create, :destroy]
  before_action :correct_user,    only: :destroy

  def index
    if user_signed_in?
      @wishlists = current_user.wishlists.all
      @wishlists_day_count = @wishlists.map do |wishlist| 

        day_count = (wishlist.due_date - Date.today).to_i
        { wishlist: wishlist, day_count: day_count }
      end
    end
  end

  def new
    @wishlist = current_user.wishlists.build
  end

  def create
    @wishlist = current_user.wishlists.build(list_params)
    if @wishlist.save 
      redirect_to wishlists_path
    else
      # flash[:errors] = @wishlist.errors.full_messages
      # redirect_to wishlists_path
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @wishlist.destroy
    flash[:success] = "Wishlist deleted"
    redirect_to wishlists_path, status: :see_other
  end

  private

  def list_params
    params.require(:wishlist).permit(:id, :list, :due_date)
  end

  def correct_user
    @wishlist = current_user.wishlists.find_by(id: params[:id])
    redirect_to wishlists_path, status: :see_other if @wishlist.nil?
  end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_wishlist.html.erb
<% if @wishlists_day_count.present? %>
  <% @wishlists_day_count.each do |w| %>
    <li class="wishlist">
      <span class="left-section">
        <strong>・<%= w[:wishlist].list %></strong>
      </span>
      <span class="right-section">
        期日：<%= w[:wishlist].due_date %>
        (残日数：<%= w[:day_count] %>)
        <em><%= link_to "削除", wishlist_path(w[:wishlist]), data: { "turbo-method": :delete } %></em>
      </span>
    </li>
  <% end %>
<% else %>
    <P class="no-data">Empty</p>
<% end %>

app/views/wishlists/index.html.erb
<% provide(:title, "Wish Lists") %>
<h1>欲しい物リスト</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <ul>
      <%= render 'wishlist' %>
    </ul>

    <%= link_to "リスト追加", new_wishlist_path %>
  </div>
</div>

app/views/wishlists/new.html.erb
<% provide(:title, "New Wish Lists") %>
<h1>新規リスト</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @wishlist) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :list, "リスト" %>
      <%= f.text_area :list, class: 'form-control' %>

      <%= f.label :due_date, "期日" %>
      <%= f.date_field :due_date, class: 'form-control' %>

      <%= f.submit "送信", class: "btn btn-primary" %>
    <% end %>
    <%= link_to "欲しい物リストに戻る", wishlists_path %>
  </div>
</div>