config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    # sessions: 'users/sessions'
  }
  # get 'users/new'
  root   'static_pages#home'
  get    "/microposts",    to: "static_pages#home"

  devise_scope :user do
    get    "/sign_in",  to: "devise/sessions#new"
    post   "/sign_in",  to: "devise/sessions#create"
    delete "/sign_out", to: "devise/sessions#destroy"
    get    "/sign_up",  to: "users/registrations#new"
    post   "/sign_up",  to: "users/registrations#create"
    get    "/edit",     to: "users/registrations#edit"
    delete "/cancel",   to: "users/registrations#cancel"
  end 

  resources :users
  resources :children, only: [:index, :create]
  resources :wishlists, only: [:new, :index, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse navbar-custom">
  <div class="container">
    <%= link_to "c-memo", root_path, id: "logo" %>
    <nav>
      <div class="navbar-header">
        <button id="hamburger" type="button" class="navbar-toggle collapsed">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul id="navbar-menu"
        class="nav navbar-nav navbar-right collapse navbar-collapse">
        <li><%= link_to "Home",   root_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Measurement", children_path %></li>
        <li><%= link_to "Wishlists", wishlists_path %></li>
        <li class="dropdown">
          <a href="#" id="account" class="dropdown-toggle">
            Account <b class="caret"></b>
          </a>
          <ul id="dropdown-menu" class="dropdown-menu">
            <li><%= link_to "Settings", edit_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Sign out", sign_out_path,
                                     data: { "turbo-method": :delete } %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign in", sign_in_path %></li>
      <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag('favicon.ico') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/chartkick@4.2.0/dist/chartkick.min.js" %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>